"""Canonical citation-inventory records and literal-key state."""

from ._contract import (
    CITATION_DOCUMENT_MAX_BIBLIOGRAPHY_ENTRIES,
    CITATION_DOCUMENT_MAX_CANONICAL_PAYLOAD_BYTES,
    CITATION_DOCUMENT_MAX_CITATION_KEY_CHARACTERS,
    CITATION_DOCUMENT_MAX_ID_BYTES,
    CITATION_DOCUMENT_MAX_KEYS,
    CITATION_DOCUMENT_MAX_OCCURRENCES,
    CITATION_DOCUMENT_MAX_SOURCE_GAPS,
    CITATION_DOCUMENT_MAX_SOURCE_PATH_BYTES,
    CITATION_DOCUMENT_MAX_TARGET_AGGREGATE_SOURCE_BYTES,
    CITATION_DOCUMENT_MAX_TARGET_RECORDS,
    CITATION_DOCUMENT_MAX_TARGET_REFERENCES_PER_RECORD,
    CITATION_DOCUMENT_MAX_TARGET_SOURCE_BYTES,
    CITATION_DOCUMENT_MAX_TARGET_SOURCE_FILES,
    CITATION_DOCUMENT_MAX_TEXT_BYTES,
)
from .base import (
    CitationContentIdentity,
    CitationSourceLocator,
    CitationTargetBibliographyEntry,
    CitationTargetGroup,
    CitationTargetOccurrence,
    CitationTargetSnapshot,
    CitationTargetSourceGap,
)
from .statuses import CitationKeyResolutionStatus

__all__ = [
    "CITATION_DOCUMENT_MAX_BIBLIOGRAPHY_ENTRIES",
    "CITATION_DOCUMENT_MAX_CANONICAL_PAYLOAD_BYTES",
    "CITATION_DOCUMENT_MAX_CITATION_KEY_CHARACTERS",
    "CITATION_DOCUMENT_MAX_ID_BYTES",
    "CITATION_DOCUMENT_MAX_KEYS",
    "CITATION_DOCUMENT_MAX_OCCURRENCES",
    "CITATION_DOCUMENT_MAX_SOURCE_GAPS",
    "CITATION_DOCUMENT_MAX_SOURCE_PATH_BYTES",
    "CITATION_DOCUMENT_MAX_TARGET_AGGREGATE_SOURCE_BYTES",
    "CITATION_DOCUMENT_MAX_TARGET_RECORDS",
    "CITATION_DOCUMENT_MAX_TARGET_REFERENCES_PER_RECORD",
    "CITATION_DOCUMENT_MAX_TARGET_SOURCE_BYTES",
    "CITATION_DOCUMENT_MAX_TARGET_SOURCE_FILES",
    "CITATION_DOCUMENT_MAX_TEXT_BYTES",
    "CitationContentIdentity",
    "CitationKeyResolutionStatus",
    "CitationSourceLocator",
    "CitationTargetBibliographyEntry",
    "CitationTargetGroup",
    "CitationTargetOccurrence",
    "CitationTargetSnapshot",
    "CitationTargetSourceGap",
]
