"""Canonical unversioned citation-document control API."""

from ._contract import (
    CITATION_DOCUMENT_MAX_AGGREGATE_EVIDENCE_IDS,
    CITATION_DOCUMENT_MAX_BIBLIOGRAPHY_ENTRIES,
    CITATION_DOCUMENT_MAX_CANONICAL_PAYLOAD_BYTES,
    CITATION_DOCUMENT_MAX_DOCUMENTS_PER_KEY,
    CITATION_DOCUMENT_MAX_EVIDENCE_IDS_PER_KEY,
    CITATION_DOCUMENT_MAX_ID_BYTES,
    CITATION_DOCUMENT_MAX_KEYS,
    CITATION_DOCUMENT_MAX_LINKS,
    CITATION_DOCUMENT_MAX_OBSERVATIONS_PER_KEY,
    CITATION_DOCUMENT_MAX_OCCURRENCES,
    CITATION_DOCUMENT_MAX_PDF_BYTES,
    CITATION_DOCUMENT_MAX_SOURCE_DOCUMENTS,
    CITATION_DOCUMENT_MAX_SOURCE_GAPS,
    CITATION_DOCUMENT_MAX_TARGET_AGGREGATE_SOURCE_BYTES,
    CITATION_DOCUMENT_MAX_TARGET_RECORDS,
    CITATION_DOCUMENT_MAX_TARGET_REFERENCES_PER_RECORD,
    CITATION_DOCUMENT_MAX_TARGET_SOURCE_BYTES,
    CITATION_DOCUMENT_MAX_TARGET_SOURCE_FILES,
    CITATION_DOCUMENT_MAX_TEXT_BYTES,
    CITATION_DOCUMENT_PROJECTION_CONTRACT_ID,
    CITATION_DOCUMENT_PROJECTOR_NAME,
    CITATION_SOURCE_DOCUMENT_LINK_CONTRACT_ID,
    CITATION_SOURCE_DOCUMENT_LINKER_NAME,
)
from .document import (
    CitationSourceDocumentDescriptor,
    CitationSourceDocumentObservation,
)
from .linkage import (
    CitationSourceDocumentLink,
    CitationSourceDocumentLinker,
    CitationSourceDocumentLinkRequest,
    CitationSourceDocumentLinkResult,
)
from .projection import (
    CitationDocumentProjection,
    CitationDocumentProjectionItem,
    CitationDocumentProjectionRequest,
    CitationDocumentProjectionResult,
    CitationDocumentProjector,
)
from .statuses import (
    CitationBibliographyMembershipStatus,
    CitationDocumentAvailabilityStatus,
    CitationKeyResolutionStatus,
)
from .target import (
    CitationBibliographyObservationBinding,
    CitationContentIdentity,
    CitationSourceLocator,
    CitationTargetBibliographyEntry,
    CitationTargetGroup,
    CitationTargetOccurrence,
    CitationTargetSnapshot,
    CitationTargetSourceGap,
)

__all__ = [
    "CITATION_DOCUMENT_MAX_AGGREGATE_EVIDENCE_IDS",
    "CITATION_DOCUMENT_MAX_BIBLIOGRAPHY_ENTRIES",
    "CITATION_DOCUMENT_MAX_CANONICAL_PAYLOAD_BYTES",
    "CITATION_DOCUMENT_MAX_DOCUMENTS_PER_KEY",
    "CITATION_DOCUMENT_MAX_EVIDENCE_IDS_PER_KEY",
    "CITATION_DOCUMENT_MAX_ID_BYTES",
    "CITATION_DOCUMENT_MAX_KEYS",
    "CITATION_DOCUMENT_MAX_LINKS",
    "CITATION_DOCUMENT_MAX_OBSERVATIONS_PER_KEY",
    "CITATION_DOCUMENT_MAX_OCCURRENCES",
    "CITATION_DOCUMENT_MAX_PDF_BYTES",
    "CITATION_DOCUMENT_MAX_SOURCE_DOCUMENTS",
    "CITATION_DOCUMENT_MAX_SOURCE_GAPS",
    "CITATION_DOCUMENT_MAX_TARGET_AGGREGATE_SOURCE_BYTES",
    "CITATION_DOCUMENT_MAX_TARGET_RECORDS",
    "CITATION_DOCUMENT_MAX_TARGET_REFERENCES_PER_RECORD",
    "CITATION_DOCUMENT_MAX_TARGET_SOURCE_BYTES",
    "CITATION_DOCUMENT_MAX_TARGET_SOURCE_FILES",
    "CITATION_DOCUMENT_MAX_TEXT_BYTES",
    "CITATION_DOCUMENT_PROJECTION_CONTRACT_ID",
    "CITATION_DOCUMENT_PROJECTOR_NAME",
    "CITATION_SOURCE_DOCUMENT_LINK_CONTRACT_ID",
    "CITATION_SOURCE_DOCUMENT_LINKER_NAME",
    "CitationBibliographyMembershipStatus",
    "CitationBibliographyObservationBinding",
    "CitationContentIdentity",
    "CitationDocumentAvailabilityStatus",
    "CitationDocumentProjection",
    "CitationDocumentProjectionItem",
    "CitationDocumentProjectionRequest",
    "CitationDocumentProjectionResult",
    "CitationDocumentProjector",
    "CitationKeyResolutionStatus",
    "CitationSourceDocumentDescriptor",
    "CitationSourceDocumentLink",
    "CitationSourceDocumentLinkRequest",
    "CitationSourceDocumentLinkResult",
    "CitationSourceDocumentLinker",
    "CitationSourceDocumentObservation",
    "CitationSourceLocator",
    "CitationTargetBibliographyEntry",
    "CitationTargetGroup",
    "CitationTargetOccurrence",
    "CitationTargetSnapshot",
    "CitationTargetSourceGap",
]
