from projectkoios.references.citations import _contract as _citation_contract
from projectkoios.references.citations._contract import (
    CITATION_DOCUMENT_MAX_BIBLIOGRAPHY_ENTRIES,
    CITATION_DOCUMENT_MAX_CANONICAL_PAYLOAD_BYTES,
    CITATION_DOCUMENT_MAX_CITATION_KEY_CHARACTERS,
    CITATION_DOCUMENT_MAX_ID_BYTES,
    CITATION_DOCUMENT_MAX_KEYS,
    CITATION_DOCUMENT_MAX_OCCURRENCES,
    CITATION_DOCUMENT_MAX_SOURCE_GAPS,
    CITATION_DOCUMENT_MAX_SOURCE_PATH_BYTES,
    CITATION_DOCUMENT_MAX_TARGET_AGGREGATE_SOURCE_BYTES,
    CITATION_DOCUMENT_MAX_TARGET_RECORDS,
    CITATION_DOCUMENT_MAX_TARGET_REFERENCES_PER_RECORD,
    CITATION_DOCUMENT_MAX_TARGET_SOURCE_BYTES,
    CITATION_DOCUMENT_MAX_TARGET_SOURCE_FILES,
    CITATION_DOCUMENT_MAX_TEXT_BYTES,
)
from projectkoios.references.citations._contract import (
    stable_id as stable_id,
)

CITATION_SOURCE_DOCUMENT_LINK_CONTRACT_ID = (
    "projectkoios.references.citation-source-document-link"
)
CITATION_DOCUMENT_PROJECTION_CONTRACT_ID = (
    "projectkoios.references.citation-document-projection"
)
CITATION_SOURCE_DOCUMENT_LINKER_NAME = (
    "projectkoios-references-citation-source-document-linker"
)
CITATION_DOCUMENT_PROJECTOR_NAME = (
    "projectkoios-references-citation-document-projector"
)

CITATION_DOCUMENT_MAX_SOURCE_DOCUMENTS = 10_000
CITATION_DOCUMENT_MAX_DOCUMENTS_PER_KEY = 256
CITATION_DOCUMENT_MAX_OBSERVATIONS_PER_KEY = 256
CITATION_DOCUMENT_MAX_EVIDENCE_IDS_PER_KEY = 256
CITATION_DOCUMENT_MAX_AGGREGATE_EVIDENCE_IDS = 10_000
CITATION_DOCUMENT_MAX_LINKS = 20_000
CITATION_DOCUMENT_MAX_PDF_BYTES = 100_000_000

_CitationDocumentContract = _citation_contract._CitationContract

__all__ = [
    "CITATION_DOCUMENT_MAX_AGGREGATE_EVIDENCE_IDS",
    "CITATION_DOCUMENT_MAX_BIBLIOGRAPHY_ENTRIES",
    "CITATION_DOCUMENT_MAX_CANONICAL_PAYLOAD_BYTES",
    "CITATION_DOCUMENT_MAX_CITATION_KEY_CHARACTERS",
    "CITATION_DOCUMENT_MAX_DOCUMENTS_PER_KEY",
    "CITATION_DOCUMENT_MAX_EVIDENCE_IDS_PER_KEY",
    "CITATION_DOCUMENT_MAX_ID_BYTES",
    "CITATION_DOCUMENT_MAX_KEYS",
    "CITATION_DOCUMENT_MAX_LINKS",
    "CITATION_DOCUMENT_MAX_OBSERVATIONS_PER_KEY",
    "CITATION_DOCUMENT_MAX_OCCURRENCES",
    "CITATION_DOCUMENT_MAX_PDF_BYTES",
    "CITATION_DOCUMENT_MAX_SOURCE_DOCUMENTS",
    "CITATION_DOCUMENT_MAX_SOURCE_GAPS",
    "CITATION_DOCUMENT_MAX_SOURCE_PATH_BYTES",
    "CITATION_DOCUMENT_MAX_TARGET_AGGREGATE_SOURCE_BYTES",
    "CITATION_DOCUMENT_MAX_TARGET_RECORDS",
    "CITATION_DOCUMENT_MAX_TARGET_REFERENCES_PER_RECORD",
    "CITATION_DOCUMENT_MAX_TARGET_SOURCE_BYTES",
    "CITATION_DOCUMENT_MAX_TARGET_SOURCE_FILES",
    "CITATION_DOCUMENT_MAX_TEXT_BYTES",
    "CITATION_DOCUMENT_PROJECTION_CONTRACT_ID",
    "CITATION_DOCUMENT_PROJECTOR_NAME",
    "CITATION_SOURCE_DOCUMENT_LINK_CONTRACT_ID",
    "CITATION_SOURCE_DOCUMENT_LINKER_NAME",
]
