from __future__ import annotations

from projectkoios.references.acquisition import (
    AcquisitionEntry,
    AcquisitionManifest,
    create_acquisition_manifest,
    verify_acquisition_manifest,
)
from projectkoios.references.assets import (
    AssetCandidate,
    AssetDiscoveryPlan,
    AssetDiscoveryPlanner,
    SearchRoot,
    materialize_asset,
)
from projectkoios.references.biblatex import (
    BibliographyImport,
    load_bibliography,
)
from projectkoios.references.catalog import ReferenceCatalog
from projectkoios.references.collection_reconciliation import (
    CitationClosure,
    CitationStatus,
    CollectionManifest,
    CollectionReconciliationError,
    CollectionReference,
    CollectionRowEvidence,
    ManagedPdf,
    PdfExpectation,
    PdfStatus,
    ProcessingEvidence,
    PublicationResult,
    ReconciliationOutputs,
    build_citation_closure,
    load_collection_rows,
    parse_reconciliation_package,
    publish_reconciliation,
    reconcile_collection,
    replay_reconciliation,
    scan_managed_pdfs,
    scan_processing_evidence,
    verify_reconciliation_package,
)
from projectkoios.references.coverage import (
    AmbiguityEvaluation,
    CandidateVersionRelation,
    CoverageAccessState,
    CoverageCandidate,
    CoverageObservation,
    CoverageState,
    ReferenceCoverage,
)
from projectkoios.references.identity import (
    ActorAuthorityScope,
    ActorKind,
    ActorProvenance,
    CanonicalPlan,
    IdentityDecision,
    IdentityDecisionKind,
    IdentityProjection,
    IdentityRecordError,
    LegacySeedMapping,
    ProducerIdentity,
    ReferenceCandidate,
    SourceBibliographyObservation,
    replay_identity_decisions,
)
from projectkoios.references.models import (
    AbstractRecord,
    CitationCandidate,
    CitationEdge,
    ReviewMembership,
    ReviewStatus,
    SourceAssetRecord,
    normalize_doi,
)
from projectkoios.references.naming import ReferenceFilenames
from projectkoios.references.path_safety import (
    AuthorizedRoot,
    PathSafetyError,
    validate_citekey,
    validate_relative_path,
)
from projectkoios.references.reconciliation_package import (
    LoadedReconciliationPackage,
    ReconciliationPackageManifest,
)

__all__ = [
    "AbstractRecord",
    "ActorAuthorityScope",
    "ActorKind",
    "ActorProvenance",
    "AmbiguityEvaluation",
    "AcquisitionEntry",
    "AcquisitionManifest",
    "AssetCandidate",
    "AuthorizedRoot",
    "AssetDiscoveryPlan",
    "AssetDiscoveryPlanner",
    "BibliographyImport",
    "CanonicalPlan",
    "CitationCandidate",
    "CitationClosure",
    "CitationEdge",
    "CandidateVersionRelation",
    "CitationStatus",
    "CollectionManifest",
    "CollectionReconciliationError",
    "CollectionReference",
    "CollectionRowEvidence",
    "CoverageAccessState",
    "CoverageCandidate",
    "CoverageObservation",
    "CoverageState",
    "IdentityDecision",
    "IdentityDecisionKind",
    "IdentityProjection",
    "IdentityRecordError",
    "LegacySeedMapping",
    "LoadedReconciliationPackage",
    "ManagedPdf",
    "PdfExpectation",
    "PathSafetyError",
    "PdfStatus",
    "ProcessingEvidence",
    "PublicationResult",
    "ReconciliationOutputs",
    "ReconciliationPackageManifest",
    "ReferenceCandidate",
    "ReferenceCoverage",
    "ReferenceCatalog",
    "ReferenceFilenames",
    "ReviewMembership",
    "ReviewStatus",
    "SearchRoot",
    "SourceAssetRecord",
    "SourceBibliographyObservation",
    "ProducerIdentity",
    "build_citation_closure",
    "create_acquisition_manifest",
    "load_bibliography",
    "load_collection_rows",
    "materialize_asset",
    "parse_reconciliation_package",
    "publish_reconciliation",
    "reconcile_collection",
    "replay_identity_decisions",
    "replay_reconciliation",
    "scan_managed_pdfs",
    "scan_processing_evidence",
    "normalize_doi",
    "validate_citekey",
    "validate_relative_path",
    "verify_acquisition_manifest",
    "verify_reconciliation_package",
]
