from __future__ import annotations

from projectkoios.references.acquisition import (
    AcquisitionEntry,
    AcquisitionManifest,
    create_acquisition_manifest,
    verify_acquisition_manifest,
)
from projectkoios.references.assets import (
    AssetCandidate,
    AssetDiscoveryPlan,
    AssetDiscoveryPlanner,
    SearchRoot,
    materialize_asset,
)
from projectkoios.references.biblatex import (
    BibliographyImport,
    load_bibliography,
)
from projectkoios.references.catalog import ReferenceCatalog
from projectkoios.references.collection_reconciliation import (
    CitationClosure,
    CitationStatus,
    CollectionManifest,
    CollectionReconciliationError,
    CollectionReference,
    CollectionRowEvidence,
    ManagedPdf,
    PdfExpectation,
    PdfStatus,
    ProcessingEvidence,
    PublicationResult,
    ReconciliationOutputs,
    build_citation_closure,
    load_collection_rows,
    publish_reconciliation,
    reconcile_collection,
    scan_managed_pdfs,
    scan_processing_evidence,
)
from projectkoios.references.models import (
    AbstractRecord,
    BibliographyOccurrence,
    CitationCandidate,
    CitationEdge,
    ReferenceAlias,
    ReferenceRecord,
    ReviewMembership,
    ReviewStatus,
    SourceAssetRecord,
    normalize_doi,
)
from projectkoios.references.naming import ReferenceFilenames
from projectkoios.references.path_safety import (
    AuthorizedRoot,
    PathSafetyError,
    validate_citekey,
    validate_relative_path,
)

__all__ = [
    "AbstractRecord",
    "AcquisitionEntry",
    "AcquisitionManifest",
    "AssetCandidate",
    "AuthorizedRoot",
    "AssetDiscoveryPlan",
    "AssetDiscoveryPlanner",
    "BibliographyImport",
    "BibliographyOccurrence",
    "CitationCandidate",
    "CitationClosure",
    "CitationEdge",
    "CitationStatus",
    "CollectionManifest",
    "CollectionReconciliationError",
    "CollectionReference",
    "CollectionRowEvidence",
    "ManagedPdf",
    "PdfExpectation",
    "PathSafetyError",
    "PdfStatus",
    "ProcessingEvidence",
    "PublicationResult",
    "ReconciliationOutputs",
    "ReferenceAlias",
    "ReferenceCatalog",
    "ReferenceFilenames",
    "ReferenceRecord",
    "ReviewMembership",
    "ReviewStatus",
    "SearchRoot",
    "SourceAssetRecord",
    "build_citation_closure",
    "create_acquisition_manifest",
    "load_bibliography",
    "load_collection_rows",
    "materialize_asset",
    "publish_reconciliation",
    "reconcile_collection",
    "scan_managed_pdfs",
    "scan_processing_evidence",
    "normalize_doi",
    "validate_citekey",
    "validate_relative_path",
    "verify_acquisition_manifest",
]
